name: Terraform Destroy

on:
  push:
    branches:
      - destroy
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  TF_VAR_env_prefix: "dev"
  TF_VAR_runner_registration_token: ${{ secrets.RUNNER_TOKEN }}
  TF_VAR_github_repo: ${{ secrets.GITHUB_REPO }}

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: self-hosted
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Set Permissions
        run: sudo chmod -R 777 $(pwd)

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Terraform Init
        run: |
          docker run --rm \
          -u $(id -u):$(id -g) \
          -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -e AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}" \
          -e TF_VAR_env_prefix="${{ env.TF_VAR_env_prefix }}" \
          -e TF_VAR_runner_registration_token="${{ secrets.RUNNER_TOKEN }}" \
          -e TF_VAR_github_repo="${{ secrets.GITHUB_REPO }}" \
          -v $(pwd):/workspace \
          -w /workspace \
          hashicorp/terraform:latest init -upgrade

      - name: Terraform Destroy
        run: |
          docker run --rm \
          -u $(id -u):$(id -g) \
          -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -e AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}" \
          -e TF_VAR_env_prefix="${{ env.TF_VAR_env_prefix }}" \
          -e TF_VAR_runner_registration_token="${{ secrets.RUNNER_TOKEN }}" \
          -e TF_VAR_github_repo="${{ secrets.GITHUB_REPO }}" \
          -v $(pwd):/workspace \
          -w /workspace \
          hashicorp/terraform:latest destroy -auto-approve

